# -- coding: utf-8 --

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
        
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 170, 321, 141))
        self.label.setStyleSheet("font: 28pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(140, 0, 20, 581))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 80, 801, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(583, 0, 20, 581))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuedit = QtWidgets.QMenu(self.menubar)
        self.menuedit.setObjectName("menuedit")
        self.menutools = QtWidgets.QMenu(self.menubar)
        self.menutools.setObjectName("menutools")
        self.menusettings = QtWidgets.QMenu(self.menubar)
        self.menusettings.setObjectName("menusettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiontools = QtWidgets.QAction(MainWindow)
        self.actiontools.setObjectName("actiontools")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionclose = QtWidgets.QAction(MainWindow)
        self.actionclose.setObjectName("actionclose")
        self.actionquit = QtWidgets.QAction(MainWindow)
        self.actionquit.setObjectName("actionquit")
        self.actioncut = QtWidgets.QAction(MainWindow)
        self.actioncut.setObjectName("actioncut")
        self.actioncopy = QtWidgets.QAction(MainWindow)
        self.actioncopy.setObjectName("actioncopy")
        self.actionpaste = QtWidgets.QAction(MainWindow)
        self.actionpaste.setObjectName("actionpaste")
        self.actiondelete = QtWidgets.QAction(MainWindow)
        self.actiondelete.setObjectName("actiondelete")
        self.actiontool1 = QtWidgets.QAction(MainWindow)
        self.actiontool1.setObjectName("actiontool1")
        self.actiontool2 = QtWidgets.QAction(MainWindow)
        self.actiontool2.setObjectName("actiontool2")
        self.actiontool3 = QtWidgets.QAction(MainWindow)
        self.actiontool3.setObjectName("actiontool3")
        self.actiontool4 = QtWidgets.QAction(MainWindow)
        self.actiontool4.setObjectName("actiontool4")
        self.actionadditional_fonts = QtWidgets.QAction(MainWindow)
        self.actionadditional_fonts.setObjectName("actionadditional_fonts")
        self.menufile.addAction(self.actionopen)
        self.menufile.addAction(self.actionsave)
        self.menufile.addAction(self.actionclose)
        self.menufile.addAction(self.actionquit)
        self.menuedit.addAction(self.actioncut)
        self.menuedit.addAction(self.actioncopy)
        self.menuedit.addAction(self.actionpaste)
        self.menuedit.addAction(self.actiondelete)
        self.menutools.addAction(self.actiontool1)
        self.menutools.addAction(self.actiontool2)
        self.menutools.addAction(self.actiontool3)
        self.menutools.addAction(self.actiontool4)
        self.menusettings.addAction(self.actionadditional_fonts)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        self.menubar.addAction(self.menutools.menuAction())
        self.menubar.addAction(self.menusettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.actionopen.triggered.connect(lambda:self.clicked("open was Clicked."))
        self.actionsave.triggered.connect(lambda:self.clicked("save was Clicked."))
        self.actionclose.triggered.connect(lambda:self.clicked("close was Clicked."))
        self.actionquit.triggered.connect(lambda:self.clicked("quit was Clicked."))
        self.actioncut.triggered.connect(lambda:self.clicked("cut was Clicked."))
        self.actioncopy.triggered.connect(lambda:self.clicked("copy Files was Clicked."))
        self.actionpaste.triggered.connect(lambda:self.clicked("paste was Clicked."))
        self.actiondelete.triggered.connect(lambda:self.clicked("delete was Clicked."))
        self.actiontool1.triggered.connect(lambda:self.clicked("tool1 was Clicked."))
        self.actiontool2.triggered.connect(lambda:self.clicked("tool2 was Clicked."))
        self.actiontool3.triggered.connect(lambda:self.clicked("tool3 was Clicked."))
        self.actiontool4.triggered.connect(lambda:self.clicked("tool4 was Clicked."))
        # self.actionOtherWindow.triggered.connect(self.newwin)
        
    def newwin(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def clicked(self,text):
        self.label.setText(text)
        self.label.adjustSize()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuedit.setTitle(_translate("MainWindow", "edit"))
        self.menutools.setTitle(_translate("MainWindow", "tools"))
        self.menusettings.setTitle(_translate("MainWindow", "settings"))
        self.actiontools.setText(_translate("MainWindow", "tools"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionopen.setToolTip(_translate("MainWindow", "open  new file"))
        self.actionopen.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionsave.setToolTip(_translate("MainWindow", "save file"))
        self.actionsave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionclose.setText(_translate("MainWindow", "close"))
        self.actionclose.setToolTip(_translate("MainWindow", "close file"))
        self.actionquit.setText(_translate("MainWindow", "quit"))
        self.actioncut.setText(_translate("MainWindow", "cut"))
        self.actioncopy.setText(_translate("MainWindow", "copy"))
        self.actioncopy.setToolTip(_translate("MainWindow", "copy file"))
        self.actioncopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionpaste.setText(_translate("MainWindow", "paste"))
        self.actionpaste.setToolTip(_translate("MainWindow", " paste file"))
        self.actionpaste.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actiondelete.setText(_translate("MainWindow", "delete"))
        self.actiontool1.setText(_translate("MainWindow", "tool1"))
        self.actiontool2.setText(_translate("MainWindow", "tool2"))
        self.actiontool3.setText(_translate("MainWindow", "tool3"))
        self.actiontool4.setText(_translate("MainWindow", "tool4"))
        self.actionadditional_fonts.setText(_translate("MainWindow", "additional fonts"))


if __name__== "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())