# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculater.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Text
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(565, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(80, 190, 61, 28))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 190, 61, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 190, 61, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 240, 61, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 240, 61, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(240, 240, 61, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(80, 300, 61, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(160, 300, 61, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(240, 300, 61, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.plus_button = QtWidgets.QPushButton(self.centralwidget)
        self.plus_button.setGeometry(QtCore.QRect(410, 160, 93, 28))
        self.plus_button.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.plus_button.setObjectName("plus_button")
        self.minus_button = QtWidgets.QPushButton(self.centralwidget)
        self.minus_button.setGeometry(QtCore.QRect(410, 210, 93, 28))
        self.minus_button.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.minus_button.setObjectName("minus_button")
        self.mul_button = QtWidgets.QPushButton(self.centralwidget)
        self.mul_button.setGeometry(QtCore.QRect(410, 260, 93, 28))
        self.mul_button.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.mul_button.setObjectName("mul_button")
        self.div_button = QtWidgets.QPushButton(self.centralwidget)
        self.div_button.setGeometry(QtCore.QRect(410, 310, 93, 28))
        self.div_button.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.div_button.setObjectName("div_button")
        self.equal_button = QtWidgets.QPushButton(self.centralwidget)
        self.equal_button.setGeometry(QtCore.QRect(410, 360, 91, 28))
        self.equal_button.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.equal_button.setObjectName("equal_button")
        self.outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel.setGeometry(QtCore.QRect(80, 60, 301, 71))
        self.outputlabel.setStyleSheet("font: 28pt \"MS Shell Dlg 2\";")
        self.outputlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputlabel.setText("")
        self.outputlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputlabel.setObjectName("outputlabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 565, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.plus_button.clicked.connect(self.plus_butt)
        self.minus_button.clicked.connect(self.min_butt)
        self.mul_button.clicked.connect(self.mul_butt)
        self.div_button.clicked.connect(self.div_butt)
        self.pushButton_1.clicked.connect(self.one_butt)
        self.pushButton_2.clicked.connect(self.two_butt)
        self.pushButton_3.clicked.connect(self.three_butt)
        self.pushButton_4.clicked.connect(self.four_butt)
        self.pushButton_5.clicked.connect(self.five_butt)
        self.pushButton_6.clicked.connect(self.six_butt)
        self.pushButton_7.clicked.connect(self.seven_butt)
        self.pushButton_8.clicked.connect(self.eight_butt)
        self.pushButton_9.clicked.connect(self.nine_butt)
        self.equal_button.clicked.connect(self.equal_butt)

    
    def plus_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"+")
        
    def min_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"-")

    def mul_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"*")

    def div_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"+/")

    def one_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"1")

    def two_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"2")

    def three_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"3")

    def four_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"4")

    def five_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"5")

    def six_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"6")

    def seven_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"7")

    def eight_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"8")

    def nine_butt(self):
        text=self.outputlabel.text()
        self.outputlabel.setText(text+"9")

    def equal_butt(self):
        text=self.outputlabel.text()
        try:
            ans=eval(text)
            self.outputlabel.setText(str(ans))
            print("Result is : ",ans)
        except:
            self.outputlabel.setText("Wrong Input")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.plus_button.setText(_translate("MainWindow", "+"))
        self.minus_button.setText(_translate("MainWindow", "-"))
        self.mul_button.setText(_translate("MainWindow", "*"))
        self.div_button.setText(_translate("MainWindow", "/"))
        self.equal_button.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
